-- Enable pgvector extension
create extension if not exists vector;

-- Create Patients Table
create table if not exists patients (
    patient_id text primary key,
    name text not null,
    age integer not null,
    past_conditions text[] default '{}'::text[],
    allergies text[] default '{}'::text[],
    current_medications text[] default '{}'::text[]
);

-- Create Patient Interactions Table
create table if not exists patient_interactions (
    id uuid default gen_random_uuid() primary key,
    patient_id text references patients(patient_id) on delete cascade,
    interaction_date date not null,
    notes text not null,
    -- 4096 is the dimension for nvidia's meta/llama3-8b-instruct or nemotron embeddings (depends on specific NVIDIA embedder used)
    -- Actually, NVIDIA's 'NV-Embed-QA' uses 1024 dimensions. We will use 1024.
    embedding vector(1024)
);

-- Insert Mock Data
insert into patients (patient_id, name, age, past_conditions, allergies, current_medications)
values 
('P001', 'John Doe', 45, '{"Hypertension", "Asthma"}', '{"Penicillin"}', '{"Lisinopril", "Albuterol Inhaler"}'),
('P002', 'Jane Smith', 30, '{"Migraines"}', '{}', '{"Ibuprofen as needed"}')
on conflict (patient_id) do nothing;

-- We'll omit mock interaction inserts here since the embeddings need to be generated by the python script before insertion.
