-- ============================================================
-- Project Baymax — Supabase Schema
-- Run this in: Supabase Dashboard → SQL Editor → New Query
-- ============================================================

-- 1. Enable pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- 2. Patients table
CREATE TABLE IF NOT EXISTS patients (
    patient_id            text PRIMARY KEY,
    name                  text NOT NULL,
    age                   integer NOT NULL,
    past_conditions       text[] DEFAULT '{}'::text[],
    allergies             text[] DEFAULT '{}'::text[],
    current_medications   text[] DEFAULT '{}'::text[]
);

-- 3. Patient interactions table (with pgvector column)
--    NVIDIA nv-embedqa-e5-v5 produces 1024-dimensional embeddings
CREATE TABLE IF NOT EXISTS patient_interactions (
    id               uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    patient_id       text REFERENCES patients(patient_id) ON DELETE CASCADE,
    interaction_date date NOT NULL,
    notes            text NOT NULL,
    embedding        vector(1024)   -- nullable until the seed script runs
);

-- 4. Index for patient lookups (foreign key)
CREATE INDEX IF NOT EXISTS idx_patient_interactions_patient_id
    ON patient_interactions(patient_id);

-- 5. HNSW index for fast ANN cosine-distance search
--    Build this AFTER seeding rows (or it will be built on-write anyway).
CREATE INDEX IF NOT EXISTS idx_patient_interactions_embedding_hnsw
    ON patient_interactions
    USING hnsw (embedding vector_cosine_ops);

-- 6. Enable RLS (required for Supabase public schema security)
ALTER TABLE patients              ENABLE ROW LEVEL SECURITY;
ALTER TABLE patient_interactions  ENABLE ROW LEVEL SECURITY;

-- 7. Seed mock patients (idempotent)
INSERT INTO patients (patient_id, name, age, past_conditions, allergies, current_medications)
VALUES
    ('P001', 'John Doe',   45, '{"Hypertension","Asthma"}',  '{"Penicillin"}',  '{"Lisinopril","Albuterol Inhaler"}'),
    ('P002', 'Jane Smith', 30, '{"Migraines"}',              '{}',              '{"Ibuprofen as needed"}')
ON CONFLICT (patient_id) DO NOTHING;

-- 8. Seed mock interactions WITHOUT embeddings
--    Embeddings are generated by `seed_supabase.py` using the NVIDIA embedder.
INSERT INTO patient_interactions (patient_id, interaction_date, notes)
VALUES
    ('P001', '2023-01-15', 'Routine checkup. BP stable.'),
    ('P001', '2023-05-20', 'Complained of mild shortness of breath. Recommended continuing inhaler.'),
    ('P001', '2023-11-02', 'Reported chest tightness during exercise. Scheduled stress test.'),
    ('P001', '2024-02-14', 'Follow-up on asthma. Lungs clear today.'),
    ('P002', '2023-08-10', 'Discussed frequency of migraines. Advised keeping a trigger journal.'),
    ('P002', '2024-01-05', 'Migraines improved. Prescribed sumatriptan for acute attacks.')
ON CONFLICT DO NOTHING;
